# Generated by Django 4.1 on 2023-11-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='char_field', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug_field', max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='shop_catego_name_289c7e_idx'),
        ),
    ]
