# Generated by Django 4.2.7 on 2023-11-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_stripe_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_product_id',
            new_name='stripe_product_price_id',
        ),
    ]
